#!/bin/bash

set -e

sudo systemctl restart web-ruby
sleep 5
echo | sudo tee /var/log/nginx/access.log

benchmarker

cat /var/log/nginx/access.log | alp ltsv -m "/api/schedules/[0-9a-zA-Z]+" --sort avg -r
